import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import { GlobalContextProvider } from "@/components/ContextProvider";
import { GlobalLoader } from "@/components/GlobalLoader";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <GlobalContextProvider>
          <main>
            <GlobalLoader />
            {children}
          </main>
        </GlobalContextProvider>
        <Toaster />
      </body>
    </html>
  );
}
