# Main config file
# Define things like DB name, ports, JWT expiry, etc.
# remember to put all the fields
database:
  host: "localhost"
  name: "compass"
  user: "this_is_mjk"

  port: 5432

rabbitmq:
  host: "localhost"
  user: "guest"
  password: "guest"
  mailqueue: "mail_queue"
  moderationqueue: "moderation_queue"
  port: 5672

ports:
  auth: 8080
  maps: 8081

smtp:
  host: smtp.gmail.com
  port: 587

domain: localhost:8080

expiry:
  emailVerification: 3